-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 16:30:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gpiygdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gpiygdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gpiygdb` DEFAULT CHARACTER SET utf8 ;
USE `gpiygdb` ;

-- -----------------------------------------------------
-- Table `gpiygdb`.`egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`egresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` DOUBLE NOT NULL,
  `moneda` VARCHAR(10) NOT NULL,
  `cotizacion` DOUBLE NULL,
  `idProveedor` INT NOT NULL,
  `idFormPago` INT NOT NULL,
  `idTipoGasto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedor_idx` (`idProveedor` ASC) VISIBLE,
  INDEX `formaPago_idx` (`idFormPago` ASC) VISIBLE,
  INDEX `destino_idx` (`idTipoGasto` ASC) VISIBLE,
  CONSTRAINT `proveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `gpiygdb`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `formaPago`
    FOREIGN KEY (`idFormPago`)
    REFERENCES `gpiygdb`.`formaPago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `destino`
    FOREIGN KEY (`idTipoGasto`)
    REFERENCES `gpiygdb`.`destino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(80) NULL,
  `cuit` VARCHAR(15) NULL,
  `rubro` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`formaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`formaPago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`destino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`fuente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`fuente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NULL,
  `direccion` VARCHAR(120) NULL,
  `cuit` VARCHAR(15) NULL,
  `comentario` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`concepto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`formaCobro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`formaCobro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`ingresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` DOUBLE NOT NULL,
  `moneda` VARCHAR(10) NOT NULL,
  `cotizacion` DOUBLE NULL,
  `idFuente` INT NOT NULL,
  `idConcepto` INT NOT NULL,
  `idFormaCobro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fuente_idx` (`idFuente` ASC) VISIBLE,
  INDEX `concepto_idx` (`idConcepto` ASC) VISIBLE,
  INDEX `cobro_idx` (`idFormaCobro` ASC) VISIBLE,
  CONSTRAINT `fuente`
    FOREIGN KEY (`idFuente`)
    REFERENCES `gpiygdb`.`fuente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `concepto`
    FOREIGN KEY (`idConcepto`)
    REFERENCES `gpiygdb`.`concepto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cobro`
    FOREIGN KEY (`idFormaCobro`)
    REFERENCES `gpiygdb`.`formaCobro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`egresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` DOUBLE NOT NULL,
  `moneda` VARCHAR(10) NOT NULL,
  `cotizacion` DOUBLE NULL,
  `idProveedor` INT NOT NULL,
  `idFormPago` INT NOT NULL,
  `idTipoGasto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedor_idx` (`idProveedor` ASC) VISIBLE,
  INDEX `formaPago_idx` (`idFormPago` ASC) VISIBLE,
  INDEX `destino_idx` (`idTipoGasto` ASC) VISIBLE,
  CONSTRAINT `proveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `gpiygdb`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `formaPago`
    FOREIGN KEY (`idFormPago`)
    REFERENCES `gpiygdb`.`formaPago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `destino`
    FOREIGN KEY (`idTipoGasto`)
    REFERENCES `gpiygdb`.`destino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`custodia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`custodia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`mercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`mercado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `comentario` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`inversiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`inversiones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `cant` INT NOT NULL,
  `idCustodia` INT NOT NULL,
  `idMercado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `custodia_idx` (`idCustodia` ASC) VISIBLE,
  INDEX `mercado_idx` (`idMercado` ASC) VISIBLE,
  CONSTRAINT `custodia`
    FOREIGN KEY (`idCustodia`)
    REFERENCES `gpiygdb`.`custodia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mercado`
    FOREIGN KEY (`idMercado`)
    REFERENCES `gpiygdb`.`mercado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`operaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `operacion` VARCHAR(45) NOT NULL,
  `cant` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `comision` DOUBLE NOT NULL,
  `idInversion` INT NOT NULL,
  `idEgreso` INT NULL,
  `idIngreso` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `inversion_idx` (`idInversion` ASC) VISIBLE,
  INDEX `egresos_idx` (`idEgreso` ASC) VISIBLE,
  CONSTRAINT `inversion`
    FOREIGN KEY (`idInversion`)
    REFERENCES `gpiygdb`.`inversiones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `egresos`
    FOREIGN KEY (`idEgreso`)
    REFERENCES `gpiygdb`.`egresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingresos`
    FOREIGN KEY (`idIngreso`)
    REFERENCES `gpiygdb`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpiygdb`.`cotizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpiygdb`.`cotizaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `idInversion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Inversiones_idx` (`idInversion` ASC) VISIBLE,
  CONSTRAINT `Inversiones`
    FOREIGN KEY (`idInversion`)
    REFERENCES `gpiygdb`.`inversiones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
